version: "3.9"
   
services:
  debug:
    image: raesene/alpine-nettools

  nginx:
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_HOST=127.0.0.1
      - DB_PORT=5432

  api:
    build: ./liveup_api/
    depends_on:
      - db 
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - .:/code
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432

  nextjs:
    build: ./liveup_web/
    environment:
      - API_URL: "http://api:8000"
      - API_URL_BROWSER: "http://142.132.174.17:8000"
    ports:
      - "3000:3000"

